### PR TITLE
add enumerables and loops intro

### PR DESCRIPTION
**Pull request by compleatang**
obviously this would not be chapter 4 but hope it is (somewhat) useful.

the example in the loops section is not the greatest and if someone can come up with a more helpful example I'm happy to refactor it.

have used ruby as the code base simply because i think it is most readable for introducing people to code but that can be refactored if that it is undesired.

### CODE REVIEW

**Comment by vdavez** [comment]
Outstanding, @compleatang! I'll review it today and see if I can figure out where it fits best!

**Comment by compleatang** [comment]
those were supposed to be two PR's rather than one. if you'd like me to redo let me know. or if you want any other changes let me know...! 

wonderful work as always Dave!

**Comment by vdavez** [comment]
So, the conditional fits into what I planned for chapter #5 (see https://github.com/vzvenyach/codingforlawyers/wiki/Table-of-Contents). 

I will likely take it and adapt it slightly, but a few comments/questions:
1. I'm torn between using ruby, python, or javascript in chapter #5. There's a part of me that wants to use JavaScript because I'm hoping to get us into the browser in a few chapters. I'm open to thoughts.
2. I'm thinking about the analogy to the Rules of Evidence critically. Maybe I'm overthinking it.. One thing that always throws me about the FRE is the balancing tests. Maybe we can integrate the notion of `prejudice > probative value`? Is that too much?
3. From a pedagogical standpoint, I'm wondering why you introduced `elsif` before `else`. My instinct was to go the other way, but that's just an instinct (not having written it yet).

**Comment by compleatang** [comment]
1. That's a tough one. I kept thinking through that yesterday. Those are the three obvious choices to start with for sure. For my money ruby is probably the easiest to read for an ultra beginner (but then I'd say that as I'm a ruby guy). That said, lots of opendata|opengov stuff is in python and obviously neither will really work in the browser. ZMQ has a thing on their site where you can select the language you want to use and it stores a cookie denoting that language. Idea could be that users would select which lang they were interested in and then the next pages would load with that lang preselected (maybe code examples could be kept in tabs). That could be overkill for now, but maybe something to consider. 
2. I'm not married to any of the examples I used. There are tons of tests which lawyers use so I think that we can come to one that works all round. Definitely in US there is the balancing test of prejudice v. probative; other jx have their own as well. 
3. That's a good point. I will try to rework that this evening.

**Comment by vdavez** [comment]
Here's where I'm at:
1. Let's do javascript. I have two reasons for this: (a) I like the fact that it actually uses human language to say `function`, `if`, `else`, `else if`; (b) I want to prepare them for JS in the browser very soon and this may be the earliest it can come in without freaking people out.
2. The FRE grew on me today. Let's go with it and add an aside about the balancing tests and conditionals.
3. You're the man.

**Comment by vdavez** [comment]
This was essentially merged in Chapter 5. Thanks again!

**Pull request closed without merging**
