### PR TITLE
Add HTML Proofer for CI

### PR DESCRIPTION
**Pull request by benbalter**
This pull requests adds a single `.travis.yml` which implements continuous integration checking via Travis CI. Specifically, on each pull request, the following will be checked:
- The site actually builds (e.g., no Jekyll syntax errors)
- All links are valid, including existence of in-site anchors
- All images are valid and have proper alt tags
- All scripts are valid

If all of the above passes, you'll see a big :green_heart: status icon on the pull request, letting you know you can merge with confidence ([example of a successful build](https://travis-ci.org/benbalter/codingforlawyers/builds/35435974)). If not, you'll see a :x:, indicating there's an error ([example of an erred build for this site](https://travis-ci.org/benbalter/codingforlawyers/builds/35435021)).

To note, in running it, it found two bad links, including a http/https swap, and a improper internal anchor.

@konklone, I know you were sensitive about not bloating the root with system files, but I think a single `.travis.yml` file (rather than e.g., a Gemfile + scripts) strikes a good balance as the feedback provided will be helpful for new users.

@vzvenyach If merged, you'll need to tell Travis to watch your Repo, which you can do in ~30 seconds by:
1. Go to https://travis-ci.org/profile
2. Oauth against GitHub
3. Click the On button next to this repo in the list

(note, the CI service is free and requires no maintenance once initially configured)

### CODE REVIEW

**Comment by vdavez** [comment]
I think this is awesome. I also think that _testing_ is such a good thing for lawyers to learn (even me), that it should be a chapter! Thanks @benbalter.

**Comment by adelevie** [comment]
I'm wondering if there are any law(yer)-specific things to mention in a testing chapter. I could see it fitting well under a larger banner of automation.

**Comment by benbalter** [comment]
> I'm wondering if there are any law(yer)-specific things to mention in a testing chapter. 

off the top of my head: Citations being valid (or common errors like spaces before/after §), reading score, using common weasel words or legal jargon?

**Comment by adelevie** [comment]
I love all of those ideas. I think a citation proofer needs to be built first before being written about ... unless one already exists?

**Pull request merged**
