### PR TITLE
A possible intro to the regular expressions.

### PR DESCRIPTION
**Pull request by tmcw**
Basically, it might be useful to introduce regex as relative to find &
replace. I'm assuming that most Word/WordPerfect users are familiar with
that interface, and showing that this is the same kind-of-thing might
make it less intimidating.

### CODE REVIEW

**Comment by mlissner** [comment]
If I recall correctly, Excel has regex support in the advanced part of the find and replace. We could really drive this home if my memory is correct (I don't have Windows, so can't check).

**Comment by mlissner** [comment]
We could even get people playing with regular expressions in Excel during the chapter!

**Comment by vdavez** [comment]
@mlissner check out the reference to MS word...

**Comment by mlissner** [comment]
Right on. Even better.

**Pull request merged**
